
  // Mock job postings data
  const [jobPostings, setJobPostings] = useState([
    {
      id: 1,
      title: "Senior Frontend Developer",
      department: "Engineering",
      location: "Arbaminch, AM",
      type: "Full-time",
      salary: "$90,000 - $120,000",
      status: "active",
      postedDate: "2025-01-15",
      applications: 12,
      description:
        "We are looking for an experienced frontend developer to join our team...",
    },
    {
      id: 2,
      title: "Marketing Manager",
      department: "Marketing",
      location: "Addis Ababa, AA",
      type: "Full-time",
      salary: "$70,000 - $90,000",
      status: "active",
      postedDate: "2025-01-10",
      applications: 8,
      description: "Lead our marketing initiatives and drive brand growth...",
    },
    {
      id: 3,
      title: "Sales Executive",
      department: "Sales",
      location: "Chencha, IL",
      type: "Full-time",
      salary: "$60,000 - $80,000",
      status: "closed",
      postedDate: "2025-01-05",
      applications: 15,
      description: "Join our sales team and help us expand our client base...",
    },
  ]);

  // Mock applicants data
  const [applicants, setApplicants] = useState([
    {
      id: 1,
      name: "Hana Jote",
      email: "hana.jote@email.com",
      phone: "+2519-2986-4782",
      position: "Senior Frontend Developer",
      jobId: 1,
      experience: "5 years",
      skills: ["React", "TypeScript", "Node.js"],
      status: "shortlisted",
      appliedDate: "2025-01-20",
      resume: "hana_jote_resume.pdf",
      rating: 4.5,
    },
    {
      id: 2,
      name: "Amanuel Admasu",
      email: "amanuel.admasu@email.com",
      phone: "+2519-8976-1732",
      position: "Marketing Manager",
      jobId: 2,
      experience: "7 years",
      skills: ["Digital Marketing", "SEO", "Analytics"],
      status: "under_review",
      appliedDate: "2025-01-18",
      resume: "amanuel_admasu_resume.pdf",
      rating: 4.2,
    },
    {
      id: 3,
      name: "Tsega Eyuel",
      email: "tsega.eyuel@email.com",
      phone: "+2519-2657-0537",
      position: "Sales Executive",
      jobId: 3,
      experience: "3 years",
      skills: ["B2B Sales", "CRM", "Lead Generation"],
      status: "rejected",
      appliedDate: "2025-01-15",
      resume: "tsega_eyuel_resume.pdf",
      rating: 3.8,
    },
    {
      id: 4,
      name: "Biruk Tesfaye",
      email: "biruk.tesfaye@email.com",
      phone: "+2519-1111-2233",
      position: "Senior Frontend Developer",
      jobId: 1,
      experience: "6 years",
      skills: ["React", "Vue.js", "GraphQL", "AWS"],
      status: "applied",
      appliedDate: "2025-08-22",
      resume: "biruk_tesfaye_resume.pdf",
      rating: 4.8,
    },
    {
      id: 5,
      name: "Temesgen Abel",
      email: "temesgen.abel@email.com",
      phone: "+2519-4444-5566",
      position: "Senior Frontend Developer",
      jobId: 1,
      experience: "4 years",
      skills: ["React", "Angular", "TypeScript"],
      status: "under_review",
      appliedDate: "2024-01-19",
      resume: "michael_davis_resume.pdf",
      rating: 4.0,
    },
  ]);